export const mockMovieData = {
    queryString: "?title_type=tv_movie&release_date=2020-01-01,2022-01-01&genres=comedy&count=5",
    results: [
        {
            id: "tt14605426",
            image: "https://imdb-api.com/images/original/MV5BZWFkM2E4ODctZGZlYi00MTY1LTg2NGMtMmZkMGVlZDE2MWU3XkEyXkFqcGdeQXVyODcyMTQ4MTc@._V1_Ratio0.6837_AL_.jpg",
            title: "Her Pen Pal",
            description: "(2021 TV Movie)",
            runtimeStr: "84 min",
            genres: "Comedy, Drama, Romance",
            genreList: [
                { key: "Comedy", value: "Comedy" },
                { key: "Drama", value: "Drama" },
                { key: "Romance", value: "Romance" },
            ],
            contentRating: "TV-G",
            imDbRating: "6.7",
            imDbRatingVotes: "1066",
            metacriticRating: null,
            plot: "Event planner Victoria can't wait to attend and plan her best friend's wedding in Paris. But when she finds out her ex is bringing a date, Victoria reconnects with her French childhood pen pal.",
            stars: "Clare Niederpruem, Mallory Jansen, Joshua Sasse, Lachlan Nieboer, Jayne Wisener",
            starList: [
                { id: "tt14605426", name: "Clare Niederpruem" },
                { id: "tt14605426", name: "Mallory Jansen" },
                { id: "tt14605426", name: "Joshua Sasse" },
                { id: "tt14605426", name: "Lachlan Nieboer" },
                { id: "tt14605426", name: "Jayne Wisener" },
            ],
        },
        {
            id: "tt14641648",
            image: "https://imdb-api.com/images/original/MV5BZDg4YTc4MWItZmNmOS00MmNiLThmMGYtYTNjNmFmOTY0Yzc2XkEyXkFqcGdeQXVyMDM0MzU2NA@@._V1_Ratio0.7449_AL_.jpg",
            title: "Psych 3: This Is Gus",
            description: "(2021 TV Movie)",
            runtimeStr: "96 min",
            genres: "Comedy, Crime, Mystery",
            genreList: [
                { key: "Comedy", value: "Comedy" },
                { key: "Crime", value: "Crime" },
                { key: "Mystery", value: "Mystery" },
            ],
            contentRating: "TV-PG",
            imDbRating: "7.7",
            imDbRatingVotes: "3078",
            metacriticRating: null,
            plot: "In preparation for a shotgun wedding before the birth of Baby Guster, Shawn and Groomzilla Gus go rogue in an attempt to track down Selene's estranged husband, as Lassiter grapples with the future of his career.",
            stars: "Steve Franks, James Roday Rodriguez, Dulé Hill, Timothy Omundson, Maggie Lawson",
            starList: [
                { id: "tt14641648", name: "Steve Franks" },
                { id: "tt14641648", name: "James Roday Rodriguez" },
                { id: "tt14641648", name: "Dulé Hill" },
                { id: "tt14641648", name: "Timothy Omundson" },
                { id: "tt14641648", name: "Maggie Lawson" },
            ],
        },
        {
            id: "tt15005868",
            image: "https://imdb-api.com/images/original/MV5BOTg5MjczMzQtZTA0Ny00OWQ1LThjNTMtYzQzYTliNzJhNjlmXkEyXkFqcGdeQXVyMDA4NzMyOA@@._V1_Ratio0.6837_AL_.jpg",
            title: "South Park: Post COVID",
            description: "(2021 TV Movie)",
            runtimeStr: "57 min",
            genres: "Animation, Comedy",
            genreList: [
                { key: "Animation", value: "Animation" },
                { key: "Comedy", value: "Comedy" },
            ],
            contentRating: "TV-MA",
            imDbRating: "7.5",
            imDbRatingVotes: "9753",
            metacriticRating: null,
            plot: "What happened to the children who lived through the Pandemic? Stan, Kyle, Cartman and Kenny survived but will never be the same Post Covid.",
            stars: "Trey Parker, Matt Stone, April Stewart, Mona Marshall",
            starList: [
                { id: "tt15005868", name: "Trey Parker" },
                { id: "tt15005868", name: "Trey Parker" },
                { id: "tt15005868", name: "Matt Stone" },
                { id: "tt15005868", name: "April Stewart" },
                { id: "tt15005868", name: "Mona Marshall" },
            ],
        },
        {
            id: "tt15112934",
            image: "https://imdb-api.com/images/original/MV5BYTI3NTdhMWEtZWE2Mi00NTBmLWJjMWYtOTAwMmJlZjc0YTZhXkEyXkFqcGdeQXVyMjkwMjY1MjI@._V1_Ratio0.6837_AL_.jpg",
            title: "Taking the Reins",
            description: "(2021 TV Movie)",
            runtimeStr: "84 min",
            genres: "Comedy, Drama, Romance",
            genreList: [
                { key: "Comedy", value: "Comedy" },
                { key: "Drama", value: "Drama" },
                { key: "Romance", value: "Romance" },
            ],
            contentRating: "TV-G",
            imDbRating: "6.3",
            imDbRatingVotes: "725",
            metacriticRating: null,
            plot: "A writer discovers what ended her marriage and why she stopped riding horses after going back to her family ranch.",
            stars: "Clare Niederpruem, Nikki Deloach, Scott Porter, Janine Turner, Eliza Hayes Maher",
            starList: [
                { id: "tt15112934", name: "Clare Niederpruem" },
                { id: "tt15112934", name: "Nikki Deloach" },
                { id: "tt15112934", name: "Scott Porter" },
                { id: "tt15112934", name: "Janine Turner" },
                { id: "tt15112934", name: "Eliza Hayes Maher" },
            ],
        },
        {
            id: "tt9766166",
            image: "https://imdb-api.com/images/original/MV5BNzVlMjA1MWMtYTk1OC00YWJjLThhNWEtOWQzMjIzMDRkMDY5XkEyXkFqcGdeQXVyNDA5NTIxMTI@._V1_Ratio0.6837_AL_.jpg",
            title: "Z-O-M-B-I-E-S 2",
            description: "(2020 TV Movie)",
            runtimeStr: "84 min",
            genres: "Comedy, Musical, Romance",
            genreList: [
                { key: "Comedy", value: "Comedy" },
                { key: "Musical", value: "Musical" },
                { key: "Romance", value: "Romance" },
            ],
            contentRating: "TV-G",
            imDbRating: "5.8",
            imDbRatingVotes: "2214",
            metacriticRating: null,
            plot: "The continuing adventures of Seabrook High students Addison and Zed, whose budding romance is threatened by the arrival of werewolves.",
            stars: "Paul Hoen, Milo Manheim, Meg Donnelly, Trevor Tordjman, Kylee Russell",
            starList: [
                { id: "tt9766166", name: "Paul Hoen" },
                { id: "tt9766166", name: "Milo Manheim" },
                { id: "tt9766166", name: "Meg Donnelly" },
                { id: "tt9766166", name: "Trevor Tordjman" },
                { id: "tt9766166", name: "Kylee Russell" },
            ],
        },
    ],
    errorMessage: null,
};

export const mockSeriesData = {
    queryString: "?title_type=tv_series&release_date=2020-01-01,2022-01-01&genres=comedy&count=5",
    results: [
        {
            id: "tt11815682",
            image: "https://imdb-api.com/images/original/MV5BZjgxODgwNTEtYjMyNC00NmM3LWEzN2QtN2RmOWY0ZDI2NmJmXkEyXkFqcGdeQXVyMTEyMjM2NDc2._V1_Ratio0.6837_AL_.jpg",
            title: "Hacks",
            description: "(2021– )",
            runtimeStr: "30 min",
            genres: "Comedy, Drama",
            genreList: [
                { key: "Comedy", value: "Comedy" },
                { key: "Drama", value: "Drama" },
            ],
            contentRating: "TV-MA",
            imDbRating: "8.2",
            imDbRatingVotes: "22825",
            metacriticRating: null,
            plot: "Explores a dark mentorship that forms between Deborah Vance, a legendary Las Vegas comedian, and an entitled, outcast 25-year-old.",
            stars: "Jean Smart, Hannah Einbinder, Carl Clemons-Hopkins, Mark Indelicato",
            starList: [
                { id: "tt11815682", name: "Jean Smart" },
                { id: "tt11815682", name: "Hannah Einbinder" },
                { id: "tt11815682", name: "Carl Clemons-Hopkins" },
                { id: "tt11815682", name: "Mark Indelicato" },
            ],
        },
        {
            id: "tt7569576",
            image: "https://imdb-api.com/images/original/MV5BOWYzN2Q0NTYtODEzMi00YWMxLWE3MDMtZGUwNGM4NjMxMzQ4XkEyXkFqcGdeQXVyODk4OTc3MTY@._V1_Ratio0.6837_AL_.jpg",
            title: "The Flight Attendant",
            description: "(2020– )",
            runtimeStr: null,
            genres: "Comedy, Drama, Mystery",
            genreList: [
                { key: "Comedy", value: "Comedy" },
                { key: "Drama", value: "Drama" },
                { key: "Mystery", value: "Mystery" },
            ],
            contentRating: "TV-MA",
            imDbRating: "7.1",
            imDbRatingVotes: "50819",
            metacriticRating: null,
            plot: "A reckless flight attendant with an alcoholism problem wakes up in the wrong hotel, in the wrong bed, with a dead man - and no idea what happened. Unable to piece the night together, she begins to wonder if she could be the killer.",
            stars: "Kaley Cuoco, Zosia Mamet, Griffin Matthews, Rosie Perez",
            starList: [
                { id: "tt7569576", name: "Kaley Cuoco" },
                { id: "tt7569576", name: "Zosia Mamet" },
                { id: "tt7569576", name: "Griffin Matthews" },
                { id: "tt7569576", name: "Rosie Perez" },
            ],
        },
        {
            id: "tt10986410",
            image: "https://imdb-api.com/images/original/MV5BMDVmODUzNmEtMGMxZC00NWUzLTkxMTAtMDM5OTQzMWE0ZDM3XkEyXkFqcGdeQXVyMDM2NDM2MQ@@._V1_Ratio0.6837_AL_.jpg",
            title: "Ted Lasso",
            description: "(2020– )",
            runtimeStr: "30 min",
            genres: "Comedy, Drama, Sport",
            genreList: [
                { key: "Comedy", value: "Comedy" },
                { key: "Drama", value: "Drama" },
                { key: "Sport", value: "Sport" },
            ],
            contentRating: "TV-MA",
            imDbRating: "8.8",
            imDbRatingVotes: "182775",
            metacriticRating: null,
            plot: "American college football coach Ted Lasso heads to London to manage AFC Richmond, a struggling English Premier League football team.",
            stars: "Jason Sudeikis, Brett Goldstein, Brendan Hunt, Nick Mohammed",
            starList: [
                { id: "tt10986410", name: "Jason Sudeikis" },
                { id: "tt10986410", name: "Brett Goldstein" },
                { id: "tt10986410", name: "Brendan Hunt" },
                { id: "tt10986410", name: "Nick Mohammed" },
            ],
        },
        {
            id: "tt12004706",
            image: "https://imdb-api.com/images/original/MV5BZDkxODJmNDktZDcxMy00MGJkLWI3NzEtNzVkYTdkZWI0ZmVkXkEyXkFqcGdeQXVyNDY4NjAxNTc@._V1_Ratio0.6837_AL_.jpg",
            title: "Panchayat",
            description: "(2020– )",
            runtimeStr: "35 min",
            genres: "Comedy, Drama",
            genreList: [
                { key: "Comedy", value: "Comedy" },
                { key: "Drama", value: "Drama" },
            ],
            contentRating: "TV-14",
            imDbRating: "8.9",
            imDbRatingVotes: "63067",
            metacriticRating: null,
            plot: "A comedy-drama, which captures the journey of an engineering graduate Abhishek, who for lack of a better job option joins as secretary of a Panchayat office in a remote village of Uttar Pradesh.",
            stars: "Jitendra Kumar, Raghuvir Yadav, Chandan Roy, Faisal Malik",
            starList: [
                { id: "tt12004706", name: "Jitendra Kumar" },
                { id: "tt12004706", name: "Raghuvir Yadav" },
                { id: "tt12004706", name: "Chandan Roy" },
                { id: "tt12004706", name: "Faisal Malik" },
            ],
        },
        {
            id: "tt8050756",
            image: "https://imdb-api.com/images/original/MV5BOGQ0MDQyYWMtNjdlYy00ZDAyLWE5YTItMzcyMjllZTA4MTcyXkEyXkFqcGdeQXVyMjEzNTg5Mzk@._V1_Ratio0.7041_AL_.jpg",
            title: "The Owl House",
            description: "(2020– )",
            runtimeStr: "22 min",
            genres: "Animation, Action, Adventure",
            genreList: [
                { key: "Animation", value: "Animation" },
                { key: "Action", value: "Action" },
                { key: "Adventure", value: "Adventure" },
            ],
            contentRating: "TV-Y7-FV",
            imDbRating: "8.1",
            imDbRatingVotes: "9649",
            metacriticRating: null,
            plot: "Accidentally sent to the world of the Boiling Isles before a trip to summer camp, a teenage human named Luz longs to become a witch, with the rebellious Eda and pint-sized demon King at her aid.",
            stars: "Sarah-Nicole Robles, Alex Hirsch, Wendie Malick, Tati Gabrielle",
            starList: [
                { id: "tt8050756", name: "Sarah-Nicole Robles" },
                { id: "tt8050756", name: "Alex Hirsch" },
                { id: "tt8050756", name: "Wendie Malick" },
                { id: "tt8050756", name: "Tati Gabrielle" },
            ],
        },
    ],
    errorMessage: null,
};

export const mockMovieItemData = {
    id: "tt9174358",
    title: "Monster Hunter: Legends of the Guild",
    originalTitle: "",
    fullTitle: "Monster Hunter: Legends of the Guild (2021)",
    type: "Movie",
    year: "2021",
    image: "https://imdb-api.com/images/original/MV5BNmMwYjQxN2QtYzc2Ni00ZGM2LTg5NTgtNzRhMjhkNjc1ZmNhXkEyXkFqcGdeQXVyMTEzMTI1Mjk3._V1_Ratio0.6751_AL_.jpg",
    releaseDate: "2021-08-12",
    runtimeMins: "PT58M",
    runtimeStr: "PT58M",
    plot: "A young man named Aiden, who calls himself a hunter, protects his isolated village. One day, he learns that his village is threatened by an Elder Dragon, a monster cloaked in mystery. Needing to find a way to save his village, Aiden leaves his home and sets off on a journey into the unknown alongside Julius, a first-rate hunter and member of the Hunter's Guild, and his companions.",
    plotLocal: "",
    plotLocalIsRtl: false,
    awards: "",
    directors: "Steve Yamamoto",
    directorList: [{ id: "nm0945493", name: "Steve Yamamoto" }],
    writers: "Joshua Fine",
    writerList: [{ id: "nm2576916", name: "Joshua Fine" }],
    stars: "Dante Basco, Erica Lindbeck, Brando Eaton",
    starList: [
        { id: "nm0002364", name: "Dante Basco" },
        { id: "nm6949652", name: "Erica Lindbeck" },
        { id: "nm2343444", name: "Brando Eaton" },
    ],
    actorList: [
        { id: "nm0002364", image: "https://imdb-api.com/images/original/MV5BMTk0MTk3MjEwOF5BMl5BanBnXkFtZTYwODA5MDU0._V1_Ratio1.0000_AL_.jpg", name: "Dante Basco", asCharacter: "Aidenas Aiden" },
        {
            id: "nm6949652",
            image: "https://imdb-api.com/images/original/MV5BNTEzYjMyOTUtZmQxNy00ZDRiLWJhMzgtMGIwYWIwNDM3YzIzXkEyXkFqcGdeQXVyOTMwMjAyMTY@._V1_Ratio1.0000_AL_.jpg",
            name: "Erica Lindbeck",
            asCharacter: "Leaas Lea",
        },
        {
            id: "nm2343444",
            image: "https://imdb-api.com/images/original/MV5BMTk4OTQzMzMwOV5BMl5BanBnXkFtZTcwNTY0MzQxMw@@._V1_Ratio1.0000_AL_.jpg",
            name: "Brando Eaton",
            asCharacter: "Juliusas Julius",
        },
        {
            id: "nm1022263",
            image: "https://imdb-api.com/images/original/MV5BMDc0OWU5M2ItZGMyZC00ODljLWIzNzktMmM4OTlhNThjMTMyXkEyXkFqcGdeQXVyMTA2MDYwODU@._V1_Ratio1.5000_AL_.jpg",
            name: "Karen Strassman",
            asCharacter: "Genovanas Genovan",
        },
        {
            id: "nm2811212",
            image: "https://imdb-api.com/images/original/MV5BYjI5ZGM1MGYtNWJmZS00ODRlLWE0YzktNmQ2NzZiMDA1ODc1XkEyXkFqcGdeQXVyNTU1OTgwOTA@._V1_Ratio1.4429_AL_.jpg",
            name: "Stephen Kramer Glickman",
            asCharacter: "Noxas Nox",
        },
        {
            id: "nm0500246",
            image: "https://imdb-api.com/images/original/MV5BYTdjNjM4MWMtOWEwNi00N2MwLTliNzUtN2ZjOGU4MDQyMTliXkEyXkFqcGdeQXVyMjQwMDg0Ng@@._V1_Ratio1.3143_AL_.jpg",
            name: "Katie Leigh",
            asCharacter: "Elder Daazelas Elder Daazel",
        },
        {
            id: "nm2696897",
            image: "https://imdb-api.com/images/original/MV5BZDhkN2JhNzMtZmMwOS00NDNlLWI3NDYtYTc5NWEwZjZjNzg1XkEyXkFqcGdeQXVyMjQwMDg0Ng@@._V1_Ratio1.0000_AL_.jpg",
            name: "G.K. Bowes",
            asCharacter: "Nadiaas Nadia",
        },
        {
            id: "nm0063527",
            image: "https://imdb-api.com/images/original/MV5BNTZhZjk4MmItYmY3OS00MWJmLWE1N2ItZGZjNWRiODYxNmFkXkEyXkFqcGdeQXVyMjQwMDg0Ng@@._V1_Ratio1.0000_AL_.jpg",
            name: "Brian Beacock",
            asCharacter: "Navidas Navid",
        },
        {
            id: "nm2094653",
            image: "https://imdb-api.com/images/original/MV5BNGM4YmYyZTItZWVmNy00MGIxLTkyMTMtYmIxZTU1YzhhNTEwXkEyXkFqcGdeQXVyMTE5NjUxODA@._V1_Ratio1.0000_AL_.jpg",
            name: "Jay Preston",
            asCharacter: "Mitulas Mitul",
        },
        { id: "nm0549007", image: "https://imdb-api.com/images/original/nopicture.jpg", name: "David Markus", asCharacter: "Farmer Burlas Farmer Burl" },
        { id: "nm12841380", image: "https://imdb-api.com/images/original/nopicture.jpg", name: "Caroline Caliston", asCharacter: "Maeas Mae" },
        { id: "nm12841381", image: "https://imdb-api.com/images/original/nopicture.jpg", name: "Dan McCoy", asCharacter: "Ravias Ravi" },
    ],
    fullCast: null,
    genres: "Animation, Action, Adventure",
    genreList: [
        { key: "Animation", value: "Animation" },
        { key: "Action", value: "Action" },
        { key: "Adventure", value: "Adventure" },
    ],
    companies: "Capcom Company, Capcom USA, Pure Imagination Studios",
    companyList: [
        { id: "co0065386", name: "Capcom Company" },
        { id: "co0330851", name: "Capcom USA" },
        { id: "co0482693", name: "Pure Imagination Studios" },
    ],
    countries: "USA, Japan",
    countryList: [
        { key: "USA", value: "USA" },
        { key: "Japan", value: "Japan" },
    ],
    languages: "English, Japanese, Italian, Portuguese, French, Spanish",
    languageList: [
        { key: "English", value: "English" },
        { key: "Japanese", value: "Japanese" },
        { key: "Italian", value: "Italian" },
        { key: "Portuguese", value: "Portuguese" },
        { key: "French", value: "French" },
        { key: "Spanish", value: "Spanish" },
    ],
    contentRating: "TV-14",
    imDbRating: "5.1",
    imDbRatingVotes: "1250",
    metacriticRating: null,
    ratings: null,
    wikipedia: null,
    posters: null,
    images: null,
    trailer: null,
    boxOffice: { budget: "", openingWeekendUSA: "", grossUSA: "", cumulativeWorldwideGross: "" },
    tagline: null,
    keywords: "hunter,hunting,dragon,monster,kaiju",
    keywordList: ["hunter", "hunting", "dragon", "monster", "kaiju"],
    similars: [
        {
            id: "tt11657662",
            title: "The Witcher: Nightmare of the Wolf",
            image: "https://imdb-api.com/images/original/MV5BY2ViMDQ3NDgtNjFkNy00ZTUzLThmMDYtYTMzY2IyZmYwNWJmXkEyXkFqcGdeQXVyMTEzMTI1Mjk3._V1_Ratio0.8019_AL_.jpg",
            imDbRating: "7.2",
        },
        {
            id: "tt14837960",
            title: "Bright: Samurai Soul",
            image: "https://imdb-api.com/images/original/MV5BYjVhN2Y2OGUtOTg3Mi00MjUyLWE2YWUtMmIxZGU1YTRjZGUwXkEyXkFqcGdeQXVyMTEzMTI1Mjk3._V1_Ratio0.6763_AL_.jpg",
            imDbRating: "5.5",
        },
        {
            id: "tt12240392",
            title: "Monster Hunter",
            image: "https://imdb-api.com/images/original/MV5BYTg4YzdlMmMtY2RmMS00ODliLWE5NzktMDJlNDdjZGQ2NGMyXkEyXkFqcGdeQXVyNTE3NzcyNjg@._V1_Ratio0.7633_AL_.jpg",
            imDbRating: "6.2",
        },
        {
            id: "tt6475714",
            title: "Monster Hunter",
            image: "https://imdb-api.com/images/original/MV5BOGU3NTFmNjYtODc3Ny00MWEzLWI3M2ItZjE3NDgwMTI0MzkzXkEyXkFqcGdeQXVyMTEyMjM2NDc2._V1_Ratio0.6763_AL_.jpg",
            imDbRating: "5.2",
        },
        {
            id: "tt13269670",
            title: "Nezha Reborn",
            image: "https://imdb-api.com/images/original/MV5BZmU0ZTQ1OWYtOTcyMi00OWVmLWJkNmEtY2I5OGEwYTJmM2Q1XkEyXkFqcGdeQXVyNDM1Nzc0MTI@._V1_Ratio0.7150_AL_.jpg",
            imDbRating: "6.8",
        },
        {
            id: "tt9310336",
            title: "Trese",
            image: "https://imdb-api.com/images/original/MV5BM2JmMzBhYWUtOGRlZi00NWE3LWJjNDgtMzc4ZWY2ZGJlMGU3XkEyXkFqcGdeQXVyMzY0MTE3NzU@._V1_Ratio0.6763_AL_.jpg",
            imDbRating: "7.0",
        },
        {
            id: "tt12808182",
            title: "The Last Mercenary",
            image: "https://imdb-api.com/images/original/MV5BNGNkZmJiZTAtY2M3MC00ZTNjLThkYmQtNmMxMTg3ZTJlNDA4XkEyXkFqcGdeQXVyMTEyMjM2NDc2._V1_Ratio0.6957_AL_.jpg",
            imDbRating: "5.3",
        },
        {
            id: "tt7737528",
            title: "Kate",
            image: "https://imdb-api.com/images/original/MV5BN2IyYzI4YmQtNzBmMi00Mjg3LWI4NTMtNmZjNjk3YjIwZmJhXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_Ratio0.6763_AL_.jpg",
            imDbRating: "6.2",
        },
        {
            id: "tt11991748",
            title: "Rurouni Kenshin: Final Chapter Part II - The Beginning",
            image: "https://imdb-api.com/images/original/MV5BMzE2YmY4NDctM2RlMi00MDg2LWI2MzYtZDQ1OWUyZjM3ZWI4XkEyXkFqcGdeQXVyMTMxNDQyNjM5._V1_Ratio0.7053_AL_.jpg",
            imDbRating: "7.4",
        },
        {
            id: "tt10731768",
            title: "Sweet Girl",
            image: "https://imdb-api.com/images/original/MV5BOGIzOTZiZjItNTMyYS00ODcyLWE2ZDUtYWNjZDNmNTUxYjVkXkEyXkFqcGdeQXVyMTEyMjM2NDc2._V1_Ratio0.6763_AL_.jpg",
            imDbRating: "5.5",
        },
        {
            id: "tt14901058",
            title: "Mortal Kombat Legends: Battle of the Realms",
            image: "https://imdb-api.com/images/original/MV5BMDU0ZDkwMzktZDA0MC00MTc5LWE1MzEtYzg2MTU5ZWE4MTU1XkEyXkFqcGdeQXVyMTY5Nzc4MDY@._V1_Ratio0.8696_AL_.jpg",
            imDbRating: "6.5",
        },
        {
            id: "tt7601480",
            title: "Major Grom: Plague Doctor",
            image: "https://imdb-api.com/images/original/MV5BMDY2Mzk1NjgtOGM2My00Yzc0LTljOWUtM2U2MWUzYTA4MzlmXkEyXkFqcGdeQXVyMjUwNjY5MzA@._V1_Ratio0.7053_AL_.jpg",
            imDbRating: "6.3",
        },
    ],
    tvSeriesInfo: null,
    tvEpisodeInfo: null,
    errorMessage: null,
};

export const mockSeriesItemData = {
    id: "tt4574334",
    title: "Stranger Things",
    originalTitle: "",
    fullTitle: "Stranger Things (TV Series 2016– )",
    type: "TVSeries",
    year: "2016",
    image: "https://imdb-api.com/images/original/MV5BODZlYjQ4NzYtZTg1MC00NGY4LTg4NjQtNGE3ZjRkMjk3YjMyXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_Ratio0.6751_AL_.jpg",
    releaseDate: "2016-07-15",
    runtimeMins: null,
    runtimeStr: null,
    plot: "In a small town where everyone knows everyone, a peculiar incident starts a chain of events that leads to a child's disappearance, which begins to tear at the fabric of an otherwise-peaceful community. Dark government agencies and seemingly malevolent supernatural forces converge on the town, while a few of the locals begin to understand that more is going on than meets the eye.",
    plotLocal: "",
    plotLocalIsRtl: false,
    awards: "Top rated TV #92 | Won 7 Primetime Emmys, 77 wins & 216 nominations total",
    directors: "",
    directorList: [],
    writers: "",
    writerList: [],
    stars: "Millie Bobby Brown, Finn Wolfhard, Winona Ryder",
    starList: [
        { id: "nm5611121", name: "Millie Bobby Brown" },
        { id: "nm6016511", name: "Finn Wolfhard" },
        { id: "nm0000213", name: "Winona Ryder" },
    ],
    actorList: [
        {
            id: "nm5611121",
            image: "https://imdb-api.com/images/original/MV5BMjA5NzA0NzQzMF5BMl5BanBnXkFtZTgwMTQxNjUzNjM@._V1_Ratio1.0000_AL_.jpg",
            name: "Millie Bobby Brown",
            asCharacter: "Elevenas Eleven",
        },
        {
            id: "nm6016511",
            image: "https://imdb-api.com/images/original/MV5BYjlkNTdhNjYtYTFhNy00MTUxLWIwNTgtMTE5NTY5Y2I3MDc0XkEyXkFqcGdeQXVyNjY5NDgzNjQ@._V1_Ratio1.0000_AL_.jpg",
            name: "Finn Wolfhard",
            asCharacter: "Mike Wheeleras Mike Wheeler",
        },
        {
            id: "nm0000213",
            image: "https://imdb-api.com/images/original/MV5BMTQ3NzM3MTc2NF5BMl5BanBnXkFtZTcwODMxNjA0NA@@._V1_Ratio1.0000_AL_.jpg",
            name: "Winona Ryder",
            asCharacter: "Joyce Byersas Joyce Byers",
        },
        {
            id: "nm1092086",
            image: "https://imdb-api.com/images/original/MV5BZTc5ODUzMDAtZGFhZS00NmExLTlhYWYtZDY0NGI2MGMwYTIzXkEyXkFqcGdeQXVyODY0MzQyODc@._V1_Ratio1.0000_AL_.jpg",
            name: "David Harbour",
            asCharacter: "Jim Hopperas Jim Hopper",
        },
        {
            id: "nm7140802",
            image: "https://imdb-api.com/images/original/MV5BNTkyNDIyMzQ5OF5BMl5BanBnXkFtZTgwNDUwMDM2NDM@._V1_Ratio1.0000_AL_.jpg",
            name: "Gaten Matarazzo",
            asCharacter: "Dustin Hendersonas Dustin Henderson",
        },
        {
            id: "nm5160895",
            image: "https://imdb-api.com/images/original/MV5BOTY2NDY0NDgwNF5BMl5BanBnXkFtZTgwNTE3NTUzNjM@._V1_Ratio1.0000_AL_.jpg",
            name: "Caleb McLaughlin",
            asCharacter: "Lucas Sinclairas Lucas Sinclair",
        },
        {
            id: "nm3034501",
            image: "https://imdb-api.com/images/original/MV5BOTIxMzc4NjI5NF5BMl5BanBnXkFtZTgwNjQ0NTUzNjM@._V1_Ratio1.5000_AL_.jpg",
            name: "Natalia Dyer",
            asCharacter: "Nancy Wheeleras Nancy Wheeler",
        },
        {
            id: "nm6390427",
            image: "https://imdb-api.com/images/original/MV5BMjEyNDUxOTAzNF5BMl5BanBnXkFtZTgwMjc3OTIxMjE@._V1_Ratio1.0000_AL_.jpg",
            name: "Charlie Heaton",
            asCharacter: "Jonathan Byersas Jonathan Byers",
        },
        {
            id: "nm6564737",
            image: "https://imdb-api.com/images/original/MV5BMzgyZjUyNzEtNmYwZi00Njg4LTgwMDktNmQ5OTc0YzdiYzY3XkEyXkFqcGdeQXVyNTk2MjUyMjA@._V1_Ratio1.0000_AL_.jpg",
            name: "Joe Keery",
            asCharacter: "Steve Harringtonas Steve Harrington",
        },
        {
            id: "nm6907855",
            image: "https://imdb-api.com/images/original/MV5BYTg1NmQwYzQtODUzYi00Y2EwLTkxMDAtNjZjZjU2Y2E3OWM5XkEyXkFqcGdeQXVyMjQwMDg0Ng@@._V1_Ratio1.0000_AL_.jpg",
            name: "Noah Schnapp",
            asCharacter: "Will Byersas Will Byers",
        },
        {
            id: "nm0120648",
            image: "https://imdb-api.com/images/original/MV5BOGNkOTUxY2EtMWI4ZS00MWVjLTkyYjctYmY1ZTljNTFmYjExXkEyXkFqcGdeQXVyMDUxNTgzNw@@._V1_Ratio1.0000_AL_.jpg",
            name: "Cara Buono",
            asCharacter: "Karen Wheeleras Karen Wheeler",
        },
        {
            id: "nm5584750",
            image: "https://imdb-api.com/images/original/MV5BYTUwZDRmNWUtMDUxMS00NTY1LWJjYTAtNjgyNTllNzZjMDFlXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_Ratio1.0000_AL_.jpg",
            name: "Sadie Sink",
            asCharacter: "Max Mayfieldas Max Mayfield",
        },
        {
            id: "nm7394207",
            image: "https://imdb-api.com/images/original/MV5BYmJhNGYzY2ItODljMC00MzYyLTk1ZGYtNzIxNjI0ODEwY2M2XkEyXkFqcGdeQXVyNjMzNjM4MDA@._V1_Ratio1.0000_AL_.jpg",
            name: "Priah Ferguson",
            asCharacter: "Erica Sinclairas Erica Sinclair",
        },
        {
            id: "nm0000546",
            image: "https://imdb-api.com/images/original/MV5BMjE3NTE4NjQxOF5BMl5BanBnXkFtZTgwMTI3MzQwNDI@._V1_Ratio1.0000_AL_.jpg",
            name: "Matthew Modine",
            asCharacter: "Martin Brenneras Martin Brenner…",
        },
        {
            id: "nm0159609",
            image: "https://imdb-api.com/images/original/MV5BZjY4NTJlNjktMWQzNy00NDVhLWJkOGUtNWZmNWUxMzEzYTdmXkEyXkFqcGdeQXVyMjIxNzUxMjY@._V1_Ratio1.0000_AL_.jpg",
            name: "Joe Chrest",
            asCharacter: "Ted Wheeleras Ted Wheeler",
        },
        {
            id: "nm4223882",
            image: "https://imdb-api.com/images/original/MV5BY2E5YmNmMmEtODNiMC00ODhkLTgwYjctNTM5ODE1YTlhMTA5XkEyXkFqcGdeQXVyMjQ0NDA5NDM@._V1_Ratio1.0000_AL_.jpg",
            name: "Dacre Montgomery",
            asCharacter: "Billy Hargroveas Billy Hargrove",
        },
        {
            id: "nm0001663",
            image: "https://imdb-api.com/images/original/MV5BMTQ1MjUwMjI4M15BMl5BanBnXkFtZTcwNzc0NTg3NA@@._V1_Ratio1.0000_AL_.jpg",
            name: "Paul Reiser",
            asCharacter: "Sam Owensas Sam Owens…",
        },
        {
            id: "nm1638321",
            image: "https://imdb-api.com/images/original/MV5BOGYzNjE2MDYtMjhhNi00MGE4LTk1ZDUtM2ZmODZlMmQ2ZjE3XkEyXkFqcGdeQXVyNjUxMjc1OTM@._V1_Ratio1.5000_AL_.jpg",
            name: "Maya Hawke",
            asCharacter: "Robin Buckleyas Robin Buckley",
        },
    ],
    fullCast: null,
    genres: "Drama, Fantasy, Horror",
    genreList: [
        { key: "Drama", value: "Drama" },
        { key: "Fantasy", value: "Fantasy" },
        { key: "Horror", value: "Horror" },
    ],
    companies: "21 Laps Entertainment, Monkey Massacre, Netflix",
    companyList: [
        { id: "co0158853", name: "21 Laps Entertainment" },
        { id: "co0598414", name: "Monkey Massacre" },
        { id: "co0144901", name: "Netflix" },
    ],
    countries: "USA",
    countryList: [{ key: "USA", value: "USA" }],
    languages: "English, Russian",
    languageList: [
        { key: "English", value: "English" },
        { key: "Russian", value: "Russian" },
    ],
    contentRating: "TV-14",
    imDbRating: "8.7",
    imDbRatingVotes: "1016510",
    metacriticRating: "74",
    ratings: null,
    wikipedia: null,
    posters: null,
    images: null,
    trailer: null,
    boxOffice: { budget: "", openingWeekendUSA: "", grossUSA: "", cumulativeWorldwideGross: "" },
    tagline: "The world is turning upside down. (Season 1)",
    keywords: "government conspiracy,1980s,friendship,monster,mk ultra",
    keywordList: ["government conspiracy", "1980s", "friendship", "monster", "mk ultra"],
    similars: [
        {
            id: "tt0944947",
            title: "Game of Thrones",
            image: "https://imdb-api.com/images/original/MV5BYTRiNDQwYzAtMzVlZS00NTI5LWJjYjUtMzkwNTUzMWMxZTllXkEyXkFqcGdeQXVyNDIzMzcwNjc@._V1_Ratio0.7343_AL_.jpg",
            imDbRating: "9.2",
        },
        {
            id: "tt0903747",
            title: "Breaking Bad",
            image: "https://imdb-api.com/images/original/MV5BODFhZjAwNjEtZDFjNi00ZTEyLThkNzUtMjZmOWM2YjQwODFmXkEyXkFqcGdeQXVyMjQwMDg0Ng@@._V1_Ratio0.6763_AL_.jpg",
            imDbRating: "9.5",
        },
        {
            id: "tt1190634",
            title: "The Boys",
            image: "https://imdb-api.com/images/original/MV5BMmM4ZGMyMTQtYmNjYS00ZmQ0LTgwMDUtYmI0YzA5ZGRlYjg5XkEyXkFqcGdeQXVyMjkwOTAyMDU@._V1_Ratio0.8019_AL_.jpg",
            imDbRating: "8.7",
        },
        {
            id: "tt2085059",
            title: "Black Mirror",
            image: "https://imdb-api.com/images/original/MV5BYTM3YWVhMDMtNjczMy00NGEyLWJhZDctYjNhMTRkNDE0ZTI1XkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_Ratio0.6763_AL_.jpg",
            imDbRating: "8.8",
        },
        {
            id: "tt1520211",
            title: "The Walking Dead",
            image: "https://imdb-api.com/images/original/MV5BZmU5NTcwNjktODIwMi00ZmZkLTk4ZWUtYzVjZWQ5ZTZjN2RlXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_Ratio0.6763_AL_.jpg",
            imDbRating: "8.2",
        },
        {
            id: "tt11225622",
            title: "Stranger Things: Spotlight",
            image: "https://imdb-api.com/images/original/MV5BMDRjYWI5NTMtZTYzZC00NTg4LWI3NjMtNmI3MTdhMWQ5MGJlXkEyXkFqcGdeQXVyNTg4MDc4Mg@@._V1_Ratio0.6763_AL_.jpg",
            imDbRating: "8.7",
        },
        {
            id: "tt8466564",
            title: "Obi-Wan Kenobi",
            image: "https://imdb-api.com/images/original/MV5BOTAxOTlmOTAtMjA0Yy00YjVjLWE3OTQtYjAzMWMxOTAwZTY1XkEyXkFqcGdeQXVyMTM1MTE1NDMx._V1_Ratio0.6763_AL_.jpg",
            imDbRating: "7.8",
        },
        {
            id: "tt1312171",
            title: "The Umbrella Academy",
            image: "https://imdb-api.com/images/original/MV5BY2VlOWMzNWUtNjU4Ny00NjBmLWE1ZWYtZDM5NDJlYzJiZjg5XkEyXkFqcGdeQXVyNjY1MTg4Mzc@._V1_Ratio0.8019_AL_.jpg",
            imDbRating: "8.0",
        },
        { id: "tt2442560", title: "Peaky Blinders", image: "https://imdb-api.com/images/original/MV5BMTkzNjEzMDEzMF5BMl5BanBnXkFtZTgwMDI0MjE4MjE@._V1_Ratio0.6763_AL_.jpg", imDbRating: "8.8" },
        {
            id: "tt8111088",
            title: "The Mandalorian",
            image: "https://imdb-api.com/images/original/MV5BZDhlMzY0ZGItZTcyNS00ZTAxLWIyMmYtZGQ2ODg5OWZiYmJkXkEyXkFqcGdeQXVyODkzNTgxMDg@._V1_Ratio0.6763_AL_.jpg",
            imDbRating: "8.7",
        },
        {
            id: "tt0386676",
            title: "The Office",
            image: "https://imdb-api.com/images/original/MV5BMDNkOTE4NDQtMTNmYi00MWE0LWE4ZTktYTc0NzhhNWIzNzJiXkEyXkFqcGdeQXVyMzQ2MDI5NjU@._V1_Ratio0.6763_AL_.jpg",
            imDbRating: "9.0",
        },
        {
            id: "tt2861424",
            title: "Rick and Morty",
            image: "https://imdb-api.com/images/original/MV5BZjRjOTFkOTktZWUzMi00YzMyLThkMmYtMjEwNmQyNzliYTNmXkEyXkFqcGdeQXVyNzQ1ODk3MTQ@._V1_Ratio0.6763_AL_.jpg",
            imDbRating: "9.2",
        },
    ],
    tvSeriesInfo: {
        yearEnd: "",
        creators: "Ross Duffer, Matt Duffer",
        creatorList: [
            { id: "nm1819973", name: "Ross Duffer" },
            { id: "nm1819972", name: "Matt Duffer" },
        ],
        seasons: ["1", "2", "3", "4"],
    },
    tvEpisodeInfo: null,
    errorMessage: null,
};

export const mockSeriesSeasonData = {
    imDbId: "tt4574334",
    title: "Stranger Things",
    fullTitle: "Stranger Things (TV Series 2016– )",
    type: "TVSeries",
    year: "2016",
    episodes: [
        {
            id: "tt4593118",
            seasonNumber: "1",
            episodeNumber: "1",
            title: "Chapter One: The Vanishing of Will Byers",
            image: "https://imdb-api.com/images/original/MV5BMTUwNTE0ODYzOF5BMl5BanBnXkFtZTgwOTc0ODE0OTE@._V1_Ratio1.7778_AL_.jpg",
            year: "2016",
            released: "15 Jul. 2016",
            plot: "At the U.S. Dept. of Energy an unexplained event occurs. Then when a young Dungeons and Dragons playing boy named Will disappears after a night with his friends, his mother Joyce and the town of Hawkins are plunged into darkness.",
            imDbRating: "8.5",
            imDbRatingCount: "22180",
        },
        {
            id: "tt4593122",
            seasonNumber: "1",
            episodeNumber: "2",
            title: "Chapter Two: The Weirdo on Maple Street",
            image: "https://imdb-api.com/images/original/MV5BYzk2YzFhM2MtNjM4Ny00NTBhLTljZTUtNzcwM2ZiMWQ3MjYwXkEyXkFqcGdeQXVyNjUxMjc1OTM@._V1_Ratio2.0000_AL_.jpg",
            year: "2016",
            released: "15 Jul. 2016",
            plot: "Mike hides the mysterious girl in his house. Joyce gets a strange phone call.",
            imDbRating: "8.4",
            imDbRatingCount: "19745",
        },
        {
            id: "tt4593126",
            seasonNumber: "1",
            episodeNumber: "3",
            title: "Chapter Three: Holly, Jolly",
            image: "https://imdb-api.com/images/original/MV5BMjMwNzQ4ODkzMl5BMl5BanBnXkFtZTgwNzY0ODE0OTE@._V1_Ratio2.0000_AL_.jpg",
            year: "2016",
            released: "15 Jul. 2016",
            plot: "An increasingly concerned Nancy looks for Barb and finds out what Jonathan's been up to. Joyce is convinced Will is trying to talk to her.",
            imDbRating: "8.8",
            imDbRatingCount: "19617",
        },
        {
            id: "tt4593124",
            seasonNumber: "1",
            episodeNumber: "4",
            title: "Chapter Four: The Body",
            image: "https://imdb-api.com/images/original/MV5BMTkwMjU2MjgzOV5BMl5BanBnXkFtZTgwMzAzOTQ5ODE@._V1_Ratio1.7778_AL_.jpg",
            year: "2016",
            released: "15 Jul. 2016",
            plot: "Refusing to believe Will is dead, Joyce tries to connect with her son. The boys give Eleven a makeover. Jonathan and Nancy form an unlikely alliance.",
            imDbRating: "8.9",
            imDbRatingCount: "19240",
        },
        {
            id: "tt4593128",
            seasonNumber: "1",
            episodeNumber: "5",
            title: "Chapter Five: The Flea and the Acrobat",
            image: "https://imdb-api.com/images/original/MV5BMjM0NjQxNTkwOF5BMl5BanBnXkFtZTgwMzY0ODE0OTE@._V1_Ratio2.0000_AL_.jpg",
            year: "2016",
            released: "15 Jul. 2016",
            plot: 'Hopper breaks into the lab to find the truth about Will\'s death. The boys try to locate the "gate" that will take them to Will.',
            imDbRating: "8.7",
            imDbRatingCount: "18211",
        },
        {
            id: "tt4593132",
            seasonNumber: "1",
            episodeNumber: "6",
            title: "Chapter Six: The Monster",
            image: "https://imdb-api.com/images/original/MV5BN2ZmNTQwYmUtMmFkMS00NjQ5LThhOWQtNGY0NWRkODgxNjk3XkEyXkFqcGdeQXVyNjczODAwNDg@._V1_Ratio2.0159_AL_.jpg",
            year: "2016",
            released: "15 Jul. 2016",
            plot: "Hopper and Joyce find the truth about the lab's experiments. After their fight, the boys look for the missing Eleven.",
            imDbRating: "8.8",
            imDbRatingCount: "18078",
        },
        {
            id: "tt4593134",
            seasonNumber: "1",
            episodeNumber: "7",
            title: "Chapter Seven: The Bathtub",
            image: "https://imdb-api.com/images/original/MV5BMjMyNTkyMTg1Ml5BMl5BanBnXkFtZTgwMjAzOTQ5ODE@._V1_Ratio1.7778_AL_.jpg",
            year: "2016",
            released: "15 Jul. 2016",
            plot: "The government comes searching for Eleven. Eleven looks for Will and Barb in the Upside Down.",
            imDbRating: "9.0",
            imDbRatingCount: "18831",
        },
        {
            id: "tt4593138",
            seasonNumber: "1",
            episodeNumber: "8",
            title: "Chapter Eight: The Upside Down",
            image: "https://imdb-api.com/images/original/MV5BMTEzNzk3MDY5MDdeQTJeQWpwZ15BbWU4MDg4NDgxNDkx._V1_Ratio1.7778_AL_.jpg",
            year: "2016",
            released: "15 Jul. 2016",
            plot: "Joyce and Hopper are taken in for questioning. Nancy and Jonathan prepare to fight the monster and save Will.",
            imDbRating: "9.3",
            imDbRatingCount: "22291",
        },
    ],
    errorMessage: "",
};

export const mockSearchData = {
    queryString: "?title=big%20bang%20theory&count=5",
    results: [
        {
            id: "tt0898266",
            image: "https://imdb-api.com/images/original/MV5BY2FmZTY5YTktOWRlYy00NmIyLWE0ZmQtZDg2YjlmMzczZDZiXkEyXkFqcGdeQXVyNjg4NzAyOTA@._V1_Ratio0.6837_AL_.jpg",
            title: "The Big Bang Theory",
            description: "(2007–2019)",
            runtimeStr: "22 min",
            genres: "Comedy, Romance",
            genreList: [
                { key: "Comedy", value: "Comedy" },
                { key: "Romance", value: "Romance" },
            ],
            contentRating: "TV-PG",
            imDbRating: "8.2",
            imDbRatingVotes: "785106",
            metacriticRating: null,
            plot: "A woman who moves into an apartment across the hall from two brilliant but socially awkward physicists shows them how little they know about life outside of the laboratory.",
            stars: "Johnny Galecki, Jim Parsons, Kaley Cuoco, Simon Helberg",
            starList: [
                { id: "tt0898266", name: "Johnny Galecki" },
                { id: "tt0898266", name: "Jim Parsons" },
                { id: "tt0898266", name: "Kaley Cuoco" },
                { id: "tt0898266", name: "Simon Helberg" },
            ],
        },
        {
            id: "tt2342339",
            image: "https://imdb-api.com/images/original/nopicture.jpg",
            title: "The Big Bang Theory: It All Started with a Big Bang",
            description: "(2012 TV Movie)",
            runtimeStr: "30 min",
            genres: "Comedy",
            genreList: [{ key: "Comedy", value: "Comedy" }],
            contentRating: null,
            imDbRating: "7.7",
            imDbRatingVotes: "362",
            metacriticRating: null,
            plot: "As the universally popular program reaches 100 episodes, this retrospective looks back on how the show started and features interviews with the now famous cast.",
            stars: "Alice Huzar, Mayim Bialik, Kaley Cuoco, Rick Edwards, Johnny Galecki",
            starList: [
                { id: "tt2342339", name: "Alice Huzar" },
                { id: "tt2342339", name: "Mayim Bialik" },
                { id: "tt2342339", name: "Kaley Cuoco" },
                { id: "tt2342339", name: "Rick Edwards" },
                { id: "tt2342339", name: "Johnny Galecki" },
            ],
        },
        {
            id: "tt10412318",
            image: "https://imdb-api.com/images/original/nopicture.jpg",
            title: "The Big Bang Theory of Everything",
            description: "(2019 TV Movie)",
            runtimeStr: null,
            genres: "Documentary",
            genreList: [{ key: "Documentary", value: "Documentary" }],
            contentRating: null,
            imDbRating: null,
            imDbRatingVotes: null,
            metacriticRating: null,
            plot: null,
            stars: "Robert Webb, Kate Bottley, Jen Brister, Nathan Caton",
            starList: [
                { id: "tt10412318", name: "Robert Webb" },
                { id: "tt10412318", name: "Kate Bottley" },
                { id: "tt10412318", name: "Jen Brister" },
                { id: "tt10412318", name: "Nathan Caton" },
            ],
        },
        {
            id: "tt1147717",
            image: "https://imdb-api.com/images/original/nopicture.jpg",
            title: "The Big Bang Theory",
            description: "(2007)",
            runtimeStr: "17 min",
            genres: "Short, Drama, Thriller",
            genreList: [
                { key: "Short", value: "Short" },
                { key: "Drama", value: "Drama" },
                { key: "Thriller", value: "Thriller" },
            ],
            contentRating: null,
            imDbRating: "8.0",
            imDbRatingVotes: "155",
            metacriticRating: null,
            plot: 'In the aftermath of September 11th and "America\'s War on Terror," two friends begin to suspect that their Middle-Eastern neighbor is a terrorist and devise a plan to investigate their suspicions.',
            stars: "Marcus Kayne, Darren Le Gallo, James Peragine, John Abiskaron",
            starList: [
                { id: "tt1147717", name: "Marcus Kayne" },
                { id: "tt1147717", name: "Darren Le Gallo" },
                { id: "tt1147717", name: "Marcus Kayne" },
                { id: "tt1147717", name: "James Peragine" },
                { id: "tt1147717", name: "John Abiskaron" },
            ],
        },
        {
            id: "tt2342337",
            image: "https://imdb-api.com/images/original/nopicture.jpg",
            title: "The Big Bang Theory: Access All Areas",
            description: "(2012 TV Movie)",
            runtimeStr: "30 min",
            genres: "Comedy",
            genreList: [{ key: "Comedy", value: "Comedy" }],
            contentRating: null,
            imDbRating: "8.1",
            imDbRatingVotes: "115",
            metacriticRating: null,
            plot: null,
            stars: "Alice Huzar, Mayim Bialik, Kaley Cuoco, Rick Edwards, Johnny Galecki",
            starList: [
                { id: "tt2342337", name: "Alice Huzar" },
                { id: "tt2342337", name: "Mayim Bialik" },
                { id: "tt2342337", name: "Kaley Cuoco" },
                { id: "tt2342337", name: "Rick Edwards" },
                { id: "tt2342337", name: "Johnny Galecki" },
            ],
        },
    ],
    errorMessage: null,
};
